# Generated by Django 4.2.1 on 2023-06-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_articul_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articul',
            name='created_at',
        ),
    ]
